# Generated by Django 4.1.6 on 2023-02-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
